config/routes.rb
Rails.application.routes.draw do
  get 'likes/index'
  get 'posts/index'
  get 'posts/show'
  get '/search', to: "posts#search"
  devise_for :users

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  root "articles#index"
  resources :users
  resources :articles do
    collection do
      post :import 
    resources :posts do
      resources :comments
      resources :likes
    end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, only: [:create, :update, :destroy]
  before_action :set_post, only: [:destroy, :create]

  def index
    @comments =  Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save 
      redirect_to article_post_path(@article, @post)
    else
      render :new
    end
  end
 
  def destroy
    @comment = @post.comments.find(id: params[:id])
    @comment.destroy
    respond_to do |format|
    format.html { redirect_to article_post_path(@article, @post), notice: 'User was successfully destroyed.' }
    format.json { head :no_content }
    format.js   { render layout: false }
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:commenter, :description, :article_id, :user_id, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/destroy.js.erb
$('.delete_comment').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/comments/index.html.erb
<h1>Comments</h1>
<% @comments.each do |comment| %>
  <ul>
    <li><%= comment.commenter %></li>
    <li><%= comment.description %></li>
  </ul>
<% end %>

app/views/comments/new.html.erb
<center><h2>Add a comment:</h2></center>
<div class="container", style="width:40rem" >
  <%= form_with model: @comment, url: article_post_comments_path do |form| %>
    <p>
      <%= form.label :commenter, class:"form-label" %><br>
      <%= form.text_field :commenter, class:"form-control" %>
    </p>
    <p>
      <%= form.label :desciption, class:"form-label" %><br>
      <%= form.text_area :description, class:"form-control" %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>