config/routes.rb
Rails.application.routes.draw do
  get 'likes/index'
  get 'posts/index'
  get 'posts/show'
  get '/search', to: "posts#search"
  devise_for :users

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  root "articles#index"
  resources :users
  resources :articles do
    collection do
      post :import 
    resources :posts do
      resources :comments
      resources :likes
    end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  validate :custom_method 
  # validates :description, presence: true
  #validate :description_method

  def custom_method
    if title.blank?
      errors.add(:title, " can not be blank ")
    elsif title.match(/\A+[[:alpha:][:blank:]]+\z/) == nil
      errors.add(:title, "please provide title only characters or spaces ")
    end
  end

  # def description_method
  #   if description.length < 30
  #     errors.add(:description, "must be provided minimum 30 characters ")
  #   end
  # end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  require 'csv'
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def import
    file = params[:file]
    return redirect_to articles_path, notice: "only csv file please" unless params[:file].content_type == "text/csv"

    filtered = []
    CSV.foreach(file, :headers => true) do |row|
      filtered << row
    end
  end

  def index
    @articles = Article.all
  end

  # def index
  #   @q = Article.ransack(params[:q])
  #   @articles = @q.result(distinct: true)
  # end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save 
      byebug
      ArticleMailer.welcome_article(@article, current_user).deliver_now
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description, :user_id, :q)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container", style="width:40rem" >
  <%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title, class:"form-label" %><br>
      <%= form.text_field :title, class:"form-control" %>
      <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :description, class:"form-label" %><br>
      <%= form.text_area :description, class:"form-control" %>
      <% @article.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div><br>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/articles/_search.html.erb
<div style="float:left;">
  <%= search_form_for @q do |f| %>
    <%= f.label :title_cont %>
    <%= f.search_field :title_cont %>
    <%= f.submit %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<body style="background-color:lightyellow;">
<h2>Edit Article</h2>
<%= render 'form' %>

app/views/articles/index.csv.erb
abc

app/views/articles/index.html.erb
<body style="background-color:lightyellow;">
<h1>Welcome</h1>
<h3>This is Article Website</h3>
<% if user_signed_in? %>
<p style = "color: green"><%= notice %></p>
<%= link_to "download as csv", articles_path(format: :csv) %>
<%= form_with url:import_articles_path, method: :post do |form| %>
<%= form.file_field :file, accept: ".csv" %>
<%= form.button "import" %>
<% end %>

<div class="container", style="float: right; width:150px;">
  <%= link_to "New Article", new_article_path, class:"btn btn-primary"%><br>
</div><br>

  <br>
  <style>
    table{width:100%; text-align:center}
  </style>
  <table class="table table-bordered border-primary">
    <center>
      <tr>
        <th style="background-color:#FFFFE0">title</th>
        <th style="background-color:#FFFFE0">Description</th>
        <th colspan = 2, style="background-color:#FFFFE0">Action</th>
      </tr>
    </center>
    <% @articles.each do |article| %>
      <tr>
        <td>
          <%= link_to article.title, article %>
        </td>
        <td>
          <%= article.description%>
        </td>
        <% if current_user.role == 'admin'|| current_user.role == 'editor' && article.user_id == current_user.id  %>
          <td>
            <%= link_to "Edit", edit_article_path(article), class:"btn btn-success" %>
          </td>
          <td>
            <%= link_to "Destroy", article_path(article),class:"btn btn-danger", data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure for delete article?"
                    }%>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/articles/new.html.erb
<body style="background-color:lightyellow;">
<center><h2>New Article</h2></center>
<%= render 'articles/form' %>
</body>

app/views/articles/show.html.erb
<body style="background-color:lightyellow;">
<%= link_to "back", root_path, class:"btn btn-success" %>
<h1>Article</h1>
<ul>
  <h4><%= @article.title %></h4>
  <h6><%= @article.description %></h6>
</ul>

  <div class="container", style="float: right; width:200px;">
    <%= link_to "New Post", new_article_post_path(@article), class:"btn btn-primary" %>
  </div>

<div class="container", style="float: right; width:600px;">
  <h2>Posts(<%= @article.posts.count %>)</h2>
  <% @article.posts.each do |post| %>
    <h3><%= link_to post.title, article_post_path(@article, post) %></h3>
    <h6><%= post.description %></h6>  
  <% end %>
  </div>
</body>