config/routes.rb
Rails.application.routes.draw do
  get 'likes/index'
  get 'posts/index'
  get 'posts/show'
  get '/search', to: "posts#search"
  devise_for :users

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  root "articles#index"
  resources :users
  resources :articles do
    collection do
      post :import 
    resources :posts do
      resources :comments
      resources :likes
    end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :article
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  #validates :title, presence: true
  validate :custom_title_valid
  validates :description,  length: { minimum: 30 }

  def custom_title_valid
    if title.blank?
      errors.add(:title, "please provide a valid title ")
    elsif title.match(/\A+[[:alpha:][:blank:]]+\z/) == nil
      errors.add(:title, "please provide title only characters or spaces ")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_article, only: [:show, :create, :update, :destroy, :index]

  def index
    if params[:search]
      @posts = Post.where('title Like ?', "%#{params[:search]}")
    else 
    @posts = Post.all
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = @article.posts.new(post_params)
    @post.user_id = current_user.id
    if @post.save 
      redirect_to article_post_path(@article, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = @article.posts.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to article_post_path(@post.article, @post)
    else
      render :edit
    end
  end

  def destroy
    @post = @article.posts.find_by(id: params[:id])
    if @post.destroy
      redirect_to root_path
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :article_id, :user_id, :search)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
<div class="container", style="width:40rem" >
  <%= form_with model: @like, url: article_post_likes_path do |form| %>
    <%= form.hidden_field :post_id, value: @post_id %>
    <%= form.submit "Like" %>
  <% end %>

app/views/posts/edit.html.erb
<body style="background-color:lightyellow;">
<%= link_to "back", article_post_path, class:"btn btn-success"%>
<center><h2>Edit Post</h2></center>
<div class="container", style="width:40rem" >
  <%= form_with model: @post, url:  article_post_path do |form| %>
    <p>
      <%= form.label :title, class:"form-label" %><br>
      <%= form.text_field :title, class:"form-control" %>
    </p>
    <p>
      <%= form.label :desciption, class:"form-label" %><br>
      <%= form.text_area :description, class:"form-control" %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>
</body>

app/views/posts/index.html.erb
<h2>Posts</h2>
<% @article.posts.each do |post| %>
  <ul>
    <h3><%= link_to post.title, article_post_path(@article, post) %></h3>
    <h6><%= post.description %></h6>
  </ul>
<% end %>
</body>

app/views/posts/new.html.erb
<body style="background-color:lightyellow;">
<center><h2>Add post:</h2></center>
<div class="container", style="width:40rem" >
  <%= form_with model: @post, url: article_posts_path do |form| %>
    <p>
      <%= form.label :title, class:"form-label" %><br>
      <%= form.text_field :title, class:"form-control" %>
      <% @post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
      <% end %>
    </p>
    <p>
      <%= form.label :desciption, class:"form-label" %><br>
      <%= form.text_area :description, class:"form-control" %>
      <% @post.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
      <% end %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>
</body>

app/views/posts/show.html.erb
 <%= link_to "back", article_path(@article), class:"btn btn-success"%>
<body style="background-color:lightyellow;">
<h1>Post</h1>
<ul>
  <h2><%= @post.title %></h2>
  <h6><%= @post.description %></h6>
</ul>
<% if current_user.role == 'admin'|| current_user.role == 'editor' && @post.user_id == current_user.id  %>
  <pre>
    <%= link_to "Edit" ,edit_article_post_path(@article, @post), class:"btn btn-primary" %>  <%= link_to "Destroy", article_post_path(@article, @post), class:"btn btn-danger", data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure for delete article?"
                    } %>
  </pre>
<% end %>

<% like = @post.likes.find { |like| like.user_id == current_user.id} %>
<% if like %> 
<div class="row">
  <span class="col-sm-1">
  <%= button_to "unlike 👎", article_post_like_path(@article, @post, like), class:"btn btn-danger", method: :delete %>
</span>
  <span class="col-sm-1">
    <%= @post.likes.count %>
  </span>
</div>
<% else %>
<div class="row">
  <span class="col-md-1">
  <%= button_to "Like 👍", article_post_likes_path(@article, @post), class:"btn btn-success", method: :post %>
</span>
<span class="col-md-1">
  <%= @post.likes.count %>
</span>
</div>
<% end %><br>
<div class="container", style="float: right; width:700px;">
  <h3>Comments(<%= @post.comments.count %>)</h3>
  <% @post.comments.each do |comment| %>
    <ul>
      <h4 style = "color: green"><%= comment.user.name %></h4>
      <h6><%= comment.description %></h6>
      <% if current_user.role == 'admin' || comment.user_id == current_user.id %>
        <%= link_to "Destroy", article_post_comment_path(@article, @post, comment), class:"btn btn-danger delete_comment", data: {
                      turbo_method: :delete, :remote => true,
                      turbo_confirm: "Are you sure for delete article?"
                    } %>
      <% end %>
    </ul>
  <% end %>
</div>
<h3>Add a comment</h3>
<div class="container", style="float: left; width:550px;">
  <%= form_with model: [@article, @post, @post.comments.build ] do |form| %>
    <p>
      <%= form.label :desciption, class:"form-label" %> <br>
      <%= form.text_area :description, class:"form-control" %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>
</body>